### ISSUE TITLE
I just read title and abstract of the paper, and before I read, I would like to know following things

### ISSUE THREAD

**Issue by nile649** [Chillee/CorrectAndSmooth#1]
1. In which aspect is the comparison is being done? GCNN are highly effective when doing clustering supervised or semi-supervised.
2. The aspect where GCNN is the first choice is when the input data is point-cloud.
I am not aware of any other case where GCNN is STOA, else if you could simplify the abstract and explain here in a few bullet points?

**Comment by Chillee** [comment]
1. In general, we focus on semi-supervised node classification tasks. The evaluation setting for the tasks in this repo can be found here: https://ogb.stanford.edu/docs/nodeprop/

2. GNNs (presumably what you mean) are the standard approach on OGB, for example: https://ogb.stanford.edu/docs/leader_nodeprop/ Other than our results, there is no non-GCN approach in the top 18 for either Arxiv nor Products. You can also take a look at leaderboards for Cora/Pubmed/Citeseer, or most other semi-supervised node classification tasks.

**Comment by nile649** [comment]
Thanks for the clarification.
