### ISSUE TITLE
About Rice31 and US County datasets

### ISSUE THREAD

**Issue by Kqiii** [Chillee/CorrectAndSmooth#3]
Hi,

Thank you for your good work! May I know where I can find the Rice31 raw data? How do you process the US County datasets from their [raw data](https://github.com/000Justin000/gnn-residual-correlation/tree/master/datasets/election)? 

It would be greatly appreciated if you could release your processed data of these two datasets.

**Comment by Chillee** [comment]
We process the US County datasets by binarizing the regression score.

I can provide the code for the US county datasets - the Rice31 data is pulled from a google drive. I'll check if we can just share that code, or whether we can rehost that data somewhere else.

**Comment by Chillee** [comment]
Rice dataset can be found here: https://archive.org/details/oxford-2005-facebook-matrix

**Comment by Kqiii** [comment]
> Rice dataset can be found here: https://archive.org/details/oxford-2005-facebook-matrix

Thank you for your reply！
