### ISSUE TITLE
Question about the implementation of label propagation

### ISSUE THREAD

**Issue by AiRyunn** [Chillee/CorrectAndSmooth#4]
Hi, I noticed that a "[clamp](https://github.com/CUAI/CorrectAndSmooth/blob/b910314a59270984f5e249462ee3faa815fc9a0c/outcome_correlation.py#L184) " operation is applied after each iteration of label propagation. Is there any paper explaining why it is need and what is the new objective function?

**Comment by Chillee** [comment]
This is a pretty standard thing to do in label propagation. For example, this one: https://www.cs.purdue.edu/homes/dgleich/publications/Ibrahim%202019%20-%20nonlinear%20diffusion.pdf (see Algorithms 1 and 2).

Note that this truncation is only applied on the Smoothing label propagation step. Applying it on the Correction step can have weird effects.
