### ISSUE TITLE
what about other datasets.

### ISSUE THREAD

**Issue by alip67** [Chillee/CorrectAndSmooth#5]
Hi, I checked the result of the paper and It seems there are more datasets that you used to compare. could you please put the code for that part as well?

**Comment by hhr114** [comment]
Same question. How can I reproduce the results on Cora, Citeseer and Pubmed?

**Comment by Chillee** [comment]
@alip67 what datasets are you interested in?

This repo was primarily meant for OGB submissions - we'll work on uploading the code for the rest.

However, I would advise against evaluating on Cora/Citeseer/Pubmed :P I think that we've already pushed up against the limits of those tiny citation datasets, and that evaluating on other benchmarks is more meaningful.

**Comment by hhr114** [comment]
@Chillee First, congratulations for the acceptance of your paper. However, I try to reimplement following the idea of the C&S paper, and it does not work on the three classic small citation networks. I want to figure out what's wrong with my implement. Can u help me?

**Comment by Chillee** [comment]
@hhr114 Thanks! The code is not very different/interesting between the different datasets. One note is that we're using  "60/20/20" split setting for Cora/Pubmed/Citeseer - I don't think our method is as effective on the "public" split (i.e: 20 nodes per class), although we didn't try very hard to tune it.

**Comment by hhr114** [comment]
@Chillee  OKay, thx for your answer. I think I already know the reason.
