### ISSUE TITLE
Question about PygNodePropPredDataset in run_experiment

### ISSUE THREAD

**Issue by TnonT** [Chillee/CorrectAndSmooth#7]
When i excute 'run_experiment.py', the code `adj, D_isqrt = process_adj(data)` in line 31 will build a undirected graph matrix.But, it can't find the edge_index in PygNodePropPredDataset from OGB. I have tried ogb=1.1.0 | 1.2.0 | 1.3.0, which have the same wrong case. Can u do me a favor. Thank you very much!

**Comment by q-hwang** [comment]
Which ogbn dataset (args.dataset) are you trying to run on specifically?

**Comment by TnonT** [comment]
arxiv

**Comment by q-hwang** [comment]
```
>>> from ogb.nodeproppred import PygNodePropPredDataset
>>> dataset = PygNodePropPredDataset(name=f'ogbn-arxiv')
>>> data = dataset[0]
>>> data.edge_index
tensor([[104447,  15858, 107156,  ...,  45118,  45118,  45118],
        [ 13091,  47283,  69161,  ..., 162473, 162537,  72717]])
>>>
```
Can you try the above commands in python and post the output? If you modified the data loading process in `run_experiment.py`, please post the alternated version.

**Comment by TnonT** [comment]
I have fixed this issue! Thanks!!!
